import Footer from '@/components/footer/Footer'
import Header from '@/components/header/Header'
import type { Metadata } from 'next'
import ClientProviders from './ClientProviders'
import styles from './globals.module.scss'
import './import-tailwind.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className="h-full" data-mode="dark">
			<body className={`${styles.body}`}>
				<ClientProviders>
					<Header />
					<main className="flex flex-col w-full flex-1 text-base/relaxed">{children}</main>
					<Footer />
				</ClientProviders>
			</body>
		</html>
	)
}
