version: '3.8'

services: 
 
  account:
    container_name: account
    build: 
      context: ./
      dockerfile: ./apps/backend/Dockerfile
      target: development
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  offers: 
    container_name: offers
    build: 
      context: ./
      dockerfile: ./apps/goods/Dockerfile
      target: development
    ports:
      - '3002:3002'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  offers-unloader: 
    container_name: offers-unloader
    build: 
      context: ./
      dockerfile: ./apps/offers-unloader/Dockerfile
      target: development
    ports:
      - '3003:3003'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    volumes: 
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env